parameters:
  name: ''
  testFiles: ''

stages: 
- stage: Test_${{ parameters.name }} 
jobs: 
- job: ${{ parameters.name }}_Windows
  pool: 
    vmImage: vs2017-win2016
steps:
- script: echo "This is template yaml! ${{ parameters.testFile }}"
